// Code generated by 'ccgo -pkgname gojp2 -trace-translation-units -export-externs X -export-defines D -export-fields F -export-structs S -export-typedefs T -I../src/lib/openjp2/ -I../src/bin/common/ ../src/bin/common/color.c ../src/lib/openjp2/bio.c ../src/lib/openjp2/cio.c ../src/lib/openjp2/dwt.c ../src/lib/openjp2/event.c ../src/lib/openjp2/function_list.c ../src/lib/openjp2/helper.c ../src/lib/openjp2/ht_dec.c ../src/lib/openjp2/image.c ../src/lib/openjp2/invert.c ../src/lib/openjp2/j2k.c ../src/lib/openjp2/jp2.c ../src/lib/openjp2/mct.c ../src/lib/openjp2/mqc.c ../src/lib/openjp2/openjpeg.c ../src/lib/openjp2/opj_malloc.c ../src/lib/openjp2/pi.c ../src/lib/openjp2/sparse_array.c ../src/lib/openjp2/t1.c ../src/lib/openjp2/t2.c ../src/lib/openjp2/tcd.c ../src/lib/openjp2/tgt.c ../src/lib/openjp2/thread.c', DO NOT EDIT.

package gojp2

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"

	"modernc.org/libc"
	"modernc.org/libc/sys/types"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer
var _ *libc.TLS
var _ types.Size_t
